package com.example.superheroes.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF984061)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFD9E2)
val md_theme_light_onPrimaryContainer = Color(0xFF3E001D)
val md_theme_light_secondary = Color(0xFFA500B2)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFFFD6F9)
val md_theme_light_onSecondaryContainer = Color(0xFF37003C)
val md_theme_light_tertiary = Color(0xFFA500B3)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFD6FA)
val md_theme_light_onTertiaryContainer = Color(0xFF37003C)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF3C0028)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF3C0028)
val md_theme_light_surfaceVariant = Color(0xFFF2DDE1)
val md_theme_light_onSurfaceVariant = Color(0xFF514347)
val md_theme_light_outline = Color(0xFF837377)
val md_theme_light_inverseOnSurface = Color(0xFFFFECF2)
val md_theme_light_inverseSurface = Color(0xFF5B113F)
val md_theme_light_inversePrimary = Color(0xFFFFB1C8)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF984061)
val md_theme_light_outlineVariant = Color(0xFFD5C2C6)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFFFB1C8)
val md_theme_dark_onPrimary = Color(0xFF5E1133)
val md_theme_dark_primaryContainer = Color(0xFF7B2949)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFD9E2)
val md_theme_dark_secondary = Color(0xFFFFA9FD)
val md_theme_dark_onSecondary = Color(0xFF590061)
val md_theme_dark_secondaryContainer = Color(0xFF7E0088)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFD6F9)
val md_theme_dark_tertiary = Color(0xFFFFA9FD)
val md_theme_dark_onTertiary = Color(0xFF590061)
val md_theme_dark_tertiaryContainer = Color(0xFF7E0089)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFD6FA)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF3C0028)
val md_theme_dark_onBackground = Color(0xFFFFD8E8)
val md_theme_dark_surface = Color(0xFF3C0028)
val md_theme_dark_onSurface = Color(0xFFFFD8E8)
val md_theme_dark_surfaceVariant = Color(0xFF514347)
val md_theme_dark_onSurfaceVariant = Color(0xFFD5C2C6)
val md_theme_dark_outline = Color(0xFF9E8C90)
val md_theme_dark_inverseOnSurface = Color(0xFF3C0028)
val md_theme_dark_inverseSurface = Color(0xFFFFD8E8)
val md_theme_dark_inversePrimary = Color(0xFF984061)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFFFB1C8)
val md_theme_dark_outlineVariant = Color(0xFF514347)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF000000)
